# Generated by Django 5.0.6 on 2024-05-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer_profile',
            old_name='eemployer_id',
            new_name='employer_id',
        ),
    ]
