# Generated by Django 5.0.6 on 2024-05-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_rename_eemployer_id_employer_profile_employer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IWO_Details_PDF',
            fields=[
                ('IWO_ID', models.AutoField(primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(max_length=20)),
                ('employee_id', models.IntegerField(max_length=20)),
                ('IWO_Status', models.CharField()),
            ],
        ),
        migrations.RenameField(
            model_name='employer_profile',
            old_name='number_of_employer',
            new_name='number_of_employees',
        ),
    ]
