# Generated by Django 5.0.4 on 2024-05-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0005_employer_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(max_length=20)),
                ('employer_id', models.IntegerField(max_length=20)),
                ('employee_name', models.CharField(max_length=50)),
                ('Garnishment_fees', models.FloatField(max_length=50)),
                ('net_pay', models.FloatField()),
                ('minimunwages', models.CharField(max_length=50)),
                ('pay', models.FloatField()),
                ('number_of_garnishment', models.CharField(max_length=50)),
            ],
        ),
    ]
