# Generated by Django 5.0.4 on 2024-05-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0006_employee_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
