# Generated by Django 5.0.4 on 2024-05-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0007_remove_customuser_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='New', max_length=10),
            preserve_default=False,
        ),
    ]
