# Generated by Django 5.0.6 on 2024-05-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0009_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='location',
            field=models.CharField(default='New', max_length=50),
            preserve_default=False,
        ),
    ]
