# Generated by Django 5.0.6 on 2024-05-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0010_employee_details_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_details',
            old_name='pay',
            new_name='pay_cycle',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='employee_id',
        ),
    ]
