# Generated by Django 5.0.6 on 2024-05-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0013_rename_minimunwages_employee_details_minimun_wages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer_profile',
            name='profile_id',
        ),
    ]
