# Generated by Django 5.0.6 on 2024-05-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0014_remove_employer_profile_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_profile',
            name='profile_id',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
