# Generated by Django 5.0.6 on 2024-05-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0017_alter_employer_profile_federal_employer_identification_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(verbose_name=20)),
                ('fedral_income_tax', models.FloatField()),
                ('social_and_security', models.FloatField()),
                ('medicare_tax', models.FloatField()),
                ('state_taxes', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='federal_employer_identification_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='number_of_employer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
