# Generated by Django 5.0.6 on 2024-05-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0018_tax_details_remove_employer_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax_details',
            name='employee_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
