# Generated by Django 5.0.6 on 2024-05-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0019_alter_tax_details_employee_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tax_details',
        ),
    ]
