# Generated by Django 5.0.6 on 2024-05-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0020_delete_tax_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(max_length=20)),
                ('fedral_income_tax', models.FloatField()),
                ('social_and_security', models.FloatField()),
                ('medicare_tax', models.FloatField()),
                ('state_taxes', models.FloatField()),
            ],
        ),
    ]
